# Generated by Django 5.1.4 on 2024-12-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date_of_recieve', models.DateField()),
                ('duration', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
                ('hours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('designation', models.CharField(choices=[('DIRECTOR', 'Director'), ('MANAGING DIRECTOR', 'Managing Director'), ('SENIOR MANAGER', 'Senior Manager'), ('SENIOR ACCOUNTANT', 'Senior Accountant'), ('PROJECT MANAGER', 'Project Manager'), ('HEAD DEVELOPER', 'Head Developer'), ('TESING ', 'Testing Lead'), ('DEVELOPER', 'Developer'), ('TESTER', 'Tester'), ('HR', 'HR')], default='DEVELOPER', max_length=100)),
                ('department', models.CharField(choices=[('ACCOUNTS', 'Accounts'), ('TESTING', 'Testing'), ('DEVELOPMENT', 'Development'), ('SALES', 'Sales'), ('SUPPORT', 'Support')], default='DEVELOPMENT', max_length=100)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
