# Generated by Django 5.1.4 on 2024-12-26 09:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='task',
            name='employee_id',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
