# Generated by Django 5.1.4 on 2024-12-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='date_of_recieve',
            new_name='date_of_receive',
        ),
        migrations.AlterField(
            model_name='project',
            name='department',
            field=models.CharField(choices=[('ACCOUNTS', 'Accounts'), ('TESTING', 'Testing'), ('DEVELOPMENT', 'Development'), ('SALES', 'Sales'), ('SUPPORT', 'Support')], max_length=100),
        ),
    ]
