# Generated by Django 5.1.4 on 2024-12-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_date_of_recieve_project_date_of_receive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_of_receive',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
