# Generated by Django 5.1.4 on 2024-12-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_task_employee_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tasks',
            field=models.ManyToManyField(related_name='projects', to='myapp.task'),
        ),
    ]
