# Generated by Django 5.1.4 on 2024-12-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_task_end_time_alter_task_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
