# Generated by Django 5.1.4 on 2024-12-26 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_task_employee_id_task_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='employee_id',
        ),
    ]
