# Generated by Django 5.1.4 on 2024-12-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_projectdepartment_remove_project_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='projects',
            field=models.ManyToManyField(null=True, related_name='employees', to='myapp.project'),
        ),
    ]
