# Generated by Django 5.1.4 on 2024-12-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_project_date_of_receive_alter_project_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('Accounts', 'Accounts'), ('Testing', 'Testing'), ('Development', 'Development'), ('Sales', 'Sales'), ('Support', 'Support')], default='Development', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(choices=[('Director', 'Director'), ('Managing Director', 'Managing Director'), ('Senior Manager', 'Senior Manager'), ('Senior Accountant', 'Senior Accountant'), ('Project Manager', 'Project Manager'), ('Head Developer', 'Head Developer'), ('Testing Lead ', 'Testing Lead'), ('Developer', 'Developer'), ('Tester', 'Tester'), ('HR', 'HR')], default='Developer', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.IntegerField(blank=True, max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='department',
            field=models.CharField(choices=[('Accounts', 'Accounts'), ('Testing', 'Testing'), ('Development', 'Development'), ('Sales', 'Sales'), ('Support', 'Support')], max_length=100),
        ),
    ]
