# Generated by Django 5.1.4 on 2024-12-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_employee_department_alter_employee_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.IntegerField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
